// <auto-generated />
using System;
using FigurasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FigurasApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250626141546_AddLargoAnchoToFigura")]
    partial class AddLargoAnchoToFigura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FigurasApi.Models.Figura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Altura")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ancho")
                        .HasColumnType("double precision");

                    b.Property<double?>("Arista")
                        .HasColumnType("double precision");

                    b.Property<double?>("Base")
                        .HasColumnType("double precision");

                    b.Property<double?>("Largo")
                        .HasColumnType("double precision");

                    b.Property<double?>("Radio")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoFigura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Volumen")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Figuras");
                });

            modelBuilder.Entity("FigurasApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
